// eslint-disable-next-line max-lines
import { IHomePageViewDataInterface } from 'src/app/view-models/home-page-view-data.interface';
export const homeData: IHomePageViewDataInterface = {
  typesOfSpeakers: {
    category: 'انواع اسپیکر',
    link: '/speakers',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/typesOfSpeakers/01.webp',
        alt: 'اسپیکر بلوتوثی کینگ استار مدل KBS157',
        title: 'اسپیکر بلوتوثی کینگ استار مدل KBS157',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/typesOfSpeakers/02.webp',
        title: 'اسپیکر بلوتوثی به همراه نور RGB طرح آدم فضایی کره ماه مدل YM-127',
        alt: 'اسپیکر بلوتوثی به همراه نور RGB طرح آدم فضایی کره ماه مدل YM-127',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/typesOfSpeakers/03.webp',
        alt: 'اسپیکر قابل حمل پاورولوژی Powerology Portable Loud Speaker',
        title: 'اسپیکر قابل حمل پاورولوژی Powerology Portable Loud Speaker',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/typesOfSpeakers/04.webp',
        alt: 'ساندبار سامسونگ مدل HW-C450',
        title: 'ساندبار سامسونگ مدل HW-C450',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/typesOfSpeakers/05.webp',
        alt: 'اسپیکر بلوتوثی ویکام 5 واتی مدل D51 برند wekome',
        title: 'اسپیکر بلوتوثی ویکام 5 واتی مدل D51 برند wekome',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/typesOfSpeakers/06.webp',
        alt: 'اسپیکر بلوتوثی قابل حمل مدل KOLAV-LJ601',
        title: 'اسپیکر بلوتوثی قابل حمل مدل KOLAV-LJ601',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/typesOfSpeakers/07.webp',
        alt: 'اسپیکر بلوتوثی کینگ استار مدل KBS156',
        title: 'اسپیکر بلوتوثی کینگ استار مدل KBS156',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/typesOfSpeakers/08.webp',
        alt: 'پخش کننده خانگی و قابل حمل سونی مدل SONY SRS-XV500',
        title: 'پخش کننده خانگی و قابل حمل سونی مدل SONY SRS-XV500',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/typesOfSpeakers/09.webp',
        alt: 'اسپیکر بلوتوثی جی بی ال مدل JBL PartyBox Stage 320',
        title: 'اسپیکر بلوتوثی جی بی ال مدل JBL PartyBox Stage 320',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/typesOfSpeakers/10.webp',
        alt: 'ساندبار سامسونگ مدل HW-B650',
        title: 'ساندبار سامسونگ مدل HW-B650',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  mobile: {
    link: '/speakers',
    category: 'گوشی موبایل',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/mobile/01.webp',
        alt: 'گوشی موبايل سامسونگ مدل Galaxy S25 FE ظرفیت ۲۵۶ گیگابایت رم ۸ گیگابایت – ویتنام',
        title: 'گوشی موبايل سامسونگ مدل Galaxy S25 FE ظرفیت ۲۵۶ گیگابایت رم ۸ گیگابایت – ویتنام',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/1.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/mobile/02.webp',
        title: 'گوشی موبایل شیائومی مدل Redmi Note 15 Pro ظرفت 256 گیگابایت رم 8 گیگابایت | 5g',
        alt: 'گوشی موبایل شیائومی مدل Redmi Note 15 Pro ظرفت 256 گیگابایت رم 8 گیگابایت | 5g',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/2.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/mobile/03.webp',
        alt: ' گوشی موبایل سامسونگ مدل Galaxy A17 4G حافظه 128 گیگابایت و رم 4 • ویتنام+شارژر سامسونگ 25 واتی + قاب + گلس',
        title:
          ' گوشی موبایل سامسونگ مدل Galaxy A17 4G حافظه 128 گیگابایت و رم 4 • ویتنام+شارژر سامسونگ 25 واتی + قاب + گلس',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/3.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/mobile/04.webp',
        alt: 'گوشی موبایل داریا Bond II 5G ظرفیت 512 گیگابایت رم 12 گیگابایت - DM-B70104',
        title: 'گوشی موبایل داریا Bond II 5G ظرفیت 512 گیگابایت رم 12 گیگابایت - DM-B70104',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/4.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/mobile/05.webp',
        alt: ' گوشی موبایل سامسونگ مدل Galaxy A56 5G دو سیم کارت ظرفیت 256 گیگابایت و رم 8 گیگابایت - ویتنام',
        title:
          ' گوشی موبایل سامسونگ مدل Galaxy A56 5G دو سیم کارت ظرفیت 256 گیگابایت و رم 8 گیگابایت - ویتنام',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/5.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/mobile/06.webp',
        alt: 'گوشی موبایل شیائومی مدل   REDMI NOTE 14 PRO 4G با ظرفیت حافظه ی 256 گیگابایت و ظرفیت رم 8 گیگ',
        title:
          'گوشی موبایل شیائومی مدل   REDMI NOTE 14 PRO 4G با ظرفیت حافظه ی 256 گیگابایت و ظرفیت رم 8 گیگ',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/6.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/mobile/07.webp',
        alt: 'گوشی موبایل شیائومی مدل Redmi Note 15 Pro Plus ظرفیت 512 گیگابایت رم 12 گیگابایت | 5G',
        title:
          'گوشی موبایل شیائومی مدل Redmi Note 15 Pro Plus ظرفیت 512 گیگابایت رم 12 گیگابایت | 5G',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/2.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/mobile/08.webp',
        alt: 'گوشی موبایل اچ ام دی مدل Pulse Pro دو سیم کارت ظرفیت 256 گیگابایت و رم 8 گیگابایت - مونتاژ ایران تحت لیسانس HMD فنلاند',
        title:
          'گوشی موبایل اچ ام دی مدل Pulse Pro دو سیم کارت ظرفیت 256 گیگابایت و رم 8 گیگابایت - مونتاژ ایران تحت لیسانس HMD فنلاند',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/4.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobile/09.webp',
        alt: ' گوشی موبايل سامسونگ مدل Galaxy A36 5G دو سیم کارت ظرفیت 256 گیگابایت رم 8 گیگابایت-ویتنام',
        title:
          ' گوشی موبايل سامسونگ مدل Galaxy A36 5G دو سیم کارت ظرفیت 256 گیگابایت رم 8 گیگابایت-ویتنام',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/5.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/mobile/10.webp',
        alt: 'گوشی موبایل تی سی ال مدل 503 TCL دو سیم کارت ظرفیت 64 گیگابایت و رم 3 گیگابایت به همراه 3 گیگابایت رم مجازی',
        title:
          'گوشی موبایل تی سی ال مدل 503 TCL دو سیم کارت ظرفیت 64 گیگابایت و رم 3 گیگابایت به همراه 3 گیگابایت رم مجازی',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobile/4.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  tabletAndLaptop: {
    link: '/speakers',
    category: 'تبلت و لپتاپ',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/tabletAndLaptop/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/tabletAndLaptop/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/tabletAndLaptop/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/tabletAndLaptop/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/tabletAndLaptop/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/tabletAndLaptop/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/tabletAndLaptop/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/tabletAndLaptop/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/tabletAndLaptop/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/tabletAndLaptop/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  powerTools: {
    link: '/powerTools',
    category: 'ابزارآلات و تجهیزات',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/powerTools/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/powerTools/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/powerTools/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/powerTools/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/powerTools/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/powerTools/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/powerTools/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/powerTools/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/powerTools/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/powerTools/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },

  goldRing: {
    link: '/goldRing',
    category: 'انگشتر طلا',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/goldRing/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/goldRing/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/goldRing/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/goldRing/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/goldRing/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/goldRing/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/goldRing/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/goldRing/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/goldRing/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/goldRing/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  goldNecklace: {
    link: '/goldNecklace',
    category: 'گردنبند طلا',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/goldNecklace/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/goldNecklace/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/goldNecklace/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/goldNecklace/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/goldNecklace/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/goldNecklace/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/goldNecklace/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/goldNecklace/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/goldNecklace/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/goldNecklace/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },

  modem: {
    link: '/modem',
    category: 'انواع مودم',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/modem/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/modem/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/modem/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'زیترو',
        imageSrc: 'assets/images/product/modem/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/zitzo.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'قشم خرید',
        imageSrc: 'assets/images/product/modem/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/gheshm.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'موبایل 140',
        imageSrc: 'assets/images/product/modem/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/140.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آی تی هوم',
        imageSrc: 'assets/images/product/modem/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/ithome.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'جی تل',
        imageSrc: 'assets/images/product/modem/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/jitel.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/modem/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیزولند',
        imageSrc: 'assets/images/product/modem/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/typesOfSpeakers/dizoland.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  smartSwitches: {
    link: '/speakers',
    category: 'کلید و پریز هوشمند',
    sliderProducts: [
      {
        id: 1,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: true,
      },
      {
        id: 2,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        fourPay: false,
      },
      {
        id: 3,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '2',
        fourPay: true,
      },
      {
        id: 4,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'آرتاالکترونیک',
        imageSrc: 'assets/images/product/smartSwitches/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  carSmartAccessories: {
    link: '/speakers',
    category: 'لوازم هوشمند خودرو',
    sliderProducts: [
      {
        id: 1,
        storeName: 'اتو جانبی',
        imageSrc: 'assets/images/product/carSmartAccessories/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 2,
        storeName: 'ای اچ سی',
        imageSrc: 'assets/images/product/carSmartAccessories/02.webp',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 3,
        storeName: 'پارتیفا',
        imageSrc: 'assets/images/product/carSmartAccessories/03.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 4,
        storeName: 'اتو جانبی',
        imageSrc: 'assets/images/product/carSmartAccessories/04.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '5',
      },
      {
        id: 5,
        storeName: 'ای اچ سی',
        imageSrc: 'assets/images/product/carSmartAccessories/05.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
        storeRate: '4.8',
      },
      {
        id: 6,
        storeName: 'پارتیفا',
        imageSrc: 'assets/images/product/carSmartAccessories/06.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'اتو جانبی',
        imageSrc: 'assets/images/product/carSmartAccessories/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'ای اچ سی',
        imageSrc: 'assets/images/product/carSmartAccessories/08.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'پارتیفا',
        imageSrc: 'assets/images/product/carSmartAccessories/09.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'اتو جانبی',
        imageSrc: 'assets/images/product/carSmartAccessories/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  mobileAccessoriesDigiLand: {
    link: '/speakers',
    category: 'موبایل و اکسسوری‌های دیجیتال دیجی‌لند',
    sliderProducts: [
      {
        id: 1,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/01.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 2,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/02.jpg',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 3,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/03.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 4,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/05.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/06.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/07.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/08.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/09.gif',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
      },
      {
        id: 10,
        storeName: 'دیجی لند',
        imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/10.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
  womenBagsAndShoes: {
    link: '/speakers',
    category: 'کیف و کفش زنانه',
    sliderProducts: [
      {
        id: 1,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 2,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/02.jpg',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 3,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/03.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 4,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/05.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/06.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/08.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/09.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
        storeRate: '5',
      },
      {
        id: 10,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
};
