FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration=production

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# اطمینان از وجود مسیر
RUN mkdir -p /usr/share/nginx/html/mydigipay

# کپی محتویات بیلد به پوشه ساب‌دومین
COPY --from=builder /app/dist/browser /usr/share/nginx/html/mydigipay

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
