FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source
COPY . .

EXPOSE 4200

# Angular Dev Server
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
