server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location = / {
        return 301 $scheme://$http_host/mydigipay/;
    }

    location /mydigipay/ {
        alias /usr/share/nginx/html/mydigipay/;
        index index.html;
        try_files $uri $uri/ /mydigipay/index.html;
    }

    location ~* \.(js|css|png|jpg|woff2|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}