import { IIncredibleDiscountDataInterface } from '@core/models/interfaces/incredible-discount-box.interface';

// eslint-disable-next-line max-lines
export const incredibleDiscountData: IIncredibleDiscountDataInterface = {
  incredibleDiscount: {
    timerEndDate: '2027-03-01T23:59:59',
    category: 'قسطی شگفت',
    sliderProducts: [
      {
        id: 1,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/01.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 2,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/02.jpg',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 3,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/03.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 4,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/04.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 5,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/05.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 6,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/06.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 7,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/07.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 8,
        storeName: 'چرم شیفر',
        imageSrc: 'assets/images/product/womenBagsAndShoes/08.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
      {
        id: 9,
        storeName: 'سانتال چرم',
        imageSrc: 'assets/images/product/womenBagsAndShoes/09.jpg',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '0',
        priceFinal: '4,500,000',
        storeRate: '5',
      },
      {
        id: 10,
        storeName: 'لباست',
        imageSrc: 'assets/images/product/womenBagsAndShoes/10.webp',
        alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
        width: '147',
        height: '147',
        storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
        priceNoDiscount: '5,500,000',
        discountPercentage: '25',
        priceFinal: '4,500,000',
      },
    ],
  },
};
