import { Component, inject, ChangeDetectorRef } from '@angular/core';
import { HeroCarouselComponent } from '../../components/hero-carousel/hero-carousel.component';
import { SquareBanner } from '../../components/square-banner/square-banner.component';
import { ServiceCardComponent } from '../../components/service-card/service-card.component';
import { ProductSectionComponent } from '../../components/product-section/product-section.component';
import { HomePageViewDataInterface } from '../../view-models/home-page-view-data.interface';
import { ListModel } from '../../@core/models/list-model';
import { ResponsiveService } from '../../@core/services/responsive.service';
import { SearchOverlayService } from '../../@core/services/search-overlay-service.service';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-home',
  imports: [
    HeroCarouselComponent,
    SquareBanner,
    ServiceCardComponent,
    ProductSectionComponent,
    NgOptimizedImage
  ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  
})
export class HomeComponent  {
  data: HomePageViewDataInterface =  {
    smartSwitches: {
      category: 'کلید و پریز هوشمند',
      sliderProducts: [
        {
          id: 1,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/01.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
          fourPay:true
        },
        {
          id: 2,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/02.webp',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
          fourPay:false

        },
        {
          id: 3,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/03.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
          storeRate:'2',
          fourPay:true

        },
        {
          id: 4,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/04.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 5,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/05.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 6,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/06.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 7,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/07.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 8,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/08.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 9,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/09.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '0',
          priceFinal: '4,500,000',
        },
        {
          id: 10,
          storeName: 'آرتاالکترونیک',
          imageSrc: 'assets/images/product/smartSwitches/10.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/smartSwitches/arta.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
      ],
    },
    carSmartAccessories: {
      category: 'لوازم هوشمند خودرو',
      sliderProducts: [
        {
          id: 1,
          storeName: 'اتو جانبی',
          imageSrc: 'assets/images/product/carSmartAccessories/01.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 2,
          storeName: 'ای اچ سی',
          imageSrc: 'assets/images/product/carSmartAccessories/02.webp',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 3,
          storeName: 'پارتیفا',
          imageSrc: 'assets/images/product/carSmartAccessories/03.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 4,
          storeName: 'اتو جانبی',
          imageSrc: 'assets/images/product/carSmartAccessories/04.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
          storeRate:'5'

        },
        {
          id: 5,
          storeName: 'ای اچ سی',
          imageSrc: 'assets/images/product/carSmartAccessories/05.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
          storeRate:'4.8'

        },
        {
          id: 6,
          storeName: 'پارتیفا',
          imageSrc: 'assets/images/product/carSmartAccessories/06.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 7,
          storeName: 'اتو جانبی',
          imageSrc: 'assets/images/product/carSmartAccessories/07.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 8,
          storeName: 'ای اچ سی',
          imageSrc: 'assets/images/product/carSmartAccessories/08.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/a-h-c.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 9,
          storeName: 'پارتیفا',
          imageSrc: 'assets/images/product/carSmartAccessories/09.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/partifa-logo.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '0',
          priceFinal: '4,500,000',
        },
        {
          id: 10,
          storeName: 'اتو جانبی',
          imageSrc: 'assets/images/product/carSmartAccessories/10.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/carSmartAccessories/auto-janebi.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
      ],
    },
    mobileAccessoriesDigiLand: {
      category: 'موبایل و اکسسوری‌های دیجیتال دیجی‌لند',
      sliderProducts: [
        {
          id: 1,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/01.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 2,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/02.jpg',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 3,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/03.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 4,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/04.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 5,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/05.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 6,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/06.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 7,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/07.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 8,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/08.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 9,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/09.gif',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '0',
          priceFinal: '4,500,000',
        },
        {
          id: 10,
          storeName: 'دیجی لند',
          imageSrc: 'assets/images/product/mobileAccessoriesDigiLand/10.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/mobileAccessoriesDigiLand/digiland.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
      ],
    },
    womenBagsAndShoes: {
      category: 'کیف و کفش زنانه',
      sliderProducts: [
        {
          id: 1,
          storeName: 'لباست',
          imageSrc: 'assets/images/product/womenBagsAndShoes/01.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 2,
          storeName: 'چرم شیفر',
          imageSrc: 'assets/images/product/womenBagsAndShoes/02.jpg',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 3,
          storeName: 'سانتال چرم',
          imageSrc: 'assets/images/product/womenBagsAndShoes/03.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 4,
          storeName: 'لباست',
          imageSrc: 'assets/images/product/womenBagsAndShoes/04.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 5,
          storeName: 'چرم شیفر',
          imageSrc: 'assets/images/product/womenBagsAndShoes/05.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 6,
          storeName: 'سانتال چرم',
          imageSrc: 'assets/images/product/womenBagsAndShoes/06.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 7,
          storeName: 'لباست',
          imageSrc: 'assets/images/product/womenBagsAndShoes/07.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 8,
          storeName: 'چرم شیفر',
          imageSrc: 'assets/images/product/womenBagsAndShoes/08.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/shifer.svg',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
        {
          id: 9,
          storeName: 'سانتال چرم',
          imageSrc: 'assets/images/product/womenBagsAndShoes/09.jpg',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/santal.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '0',
          priceFinal: '4,500,000',
          storeRate:'5'
        },
        {
          id: 10,
          storeName: 'لباست',
          imageSrc: 'assets/images/product/womenBagsAndShoes/10.webp',
          alt: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          title: 'کلید لمسی هوشمند چهار پل Zigbee نستک سری INNOVA کد NE5LS01XG4',
          width: '147',
          height: '147',
          storeLogoSrc: 'assets/images/product/womenBagsAndShoes/lebaset.webp',
          priceNoDiscount: '5,500,000',
          discountPercentage: '25',
          priceFinal: '4,500,000',
        },
      ],
    },
  };
  searchOverlay = inject(SearchOverlayService);
  responsive = inject(ResponsiveService);
  cdr = inject(ChangeDetectorRef);

  get sections() {
    if (!this.data) return [];
    return Object?.values(this?.data).map((section, index) => ({
      id: index + 1,
      ...section,
      products: new ListModel(section?.sliderProducts || []),
    }));
  }
}
